### ISSUE TITLE
Properly Handle 429 Reponse

### ISSUE THREAD

**Issue by nZac** [linode/linodego#69] opened 2019-01-28 16:02 UTC
Thanks for the library!

An issue I found when using the new Terraform provider for linode (which leverages this package) is that I hit API limits pretty quickly. The initial suggestion from your support team when I asked for an API limit increase was to decrease parallelism. As a short-term, that is fine, and I can target resources individually. However, I would love to see Linode-Go handle this issue directly by implementing retry / backup logic in the request workflow.

A quick walk through of the code (I am not a Go developer, so take this with a grain of salt) makes it look like you could use the Retry logic in Go-Resty in a straight forward way. See here: https://github.com/go-resty/resty#retries

**Comment by displague** [comment] 2019-01-28 19:57
Thanks, @nZac!

Work on this was started in #19. Since that PR was created, the Linode API rate limits were increased.  Since users were not actively encountering this, #19 became less of a priority.    Having limits in place makes things safer for users with run away jobs.  The Terraform provider's nightly tests are running with reduced parallelism because the tests are not made to approximate a real-world environment.

That said, there are going to be valid use cases for the Terraform Provider to be able to handle more resources without crashing on rate limited requests.  Likewise, there are tools depending on this library outside of Terraform, and those will want to be able to take advantage of rate limiting controls and retries too.

Issues like what you are reporting motivate development work -- thanks.  

The PR should be relatively small. I believe I was having a hard time reproducing the issue using  `make test`, because the testing tool in place doesn't allow for the same URL to be tested twice in a row with the only difference being the response headers.  I'll get this topic bubbled.

Feel free to join us in #linodego in the Gopher's Slack (or #linode in the Kubernetes Slack) for more discussion on this and related topics.

**Comment by nZac** [comment] 2019-10-30 22:39
@jnschaeffer if I can be of any use in moving this forward please let me know. It is one of those little annoyances when I am working that I would love to see disappear. Happy to beta test code that you are working through.

**Comment by phillc** [comment] 2020-02-19 13:18
This will be addressed in #126

**Closed by phillc** 2020-02-19 13:18 UTC
